lumen:
  image: yamaszone/nginx-laravel-lumen:v0.1.0
  build: .
  ports:
    - "8000:80"
    - "443:443"
    - "9000:9000"
  links:
    - postgres:postgres
  volumes:
    - ./www:/var/www
    - ./sites:/etc/nginx/conf.d
    - ./logs:/var/log/supervisor

postgres:
  image: postgres:9.5
  ports:
    - "5433:5432"
  environment:
    POSTGRES_PASSWORD: password

