#!/bin/bash

help(){
	echo "Usage:"
	printf "\t down\t\t: Stop Lumen app.\n"
	printf "\t e, enter\t: Enter Lumen container.\n"
	printf "\t example\t: Send an example request to sample Lumen app.\n"
	printf "\t h, help\t: Show this help.\n"
	printf "\t t, tests\t: Run BATS tests for Lumen app.\n"
	printf "\t up\t\t: Launch Lumen app.\n"
	exit 0
}

if [[ -z $1 ]];then
	help
	exit 0
fi

case $1 in
	up)
		sudo docker-compose up -d
		;;
	down)
		sudo docker-compose down
		;;
	e | enter)
		POSTGES_HOST_IP_ADDR=$(sudo docker-compose exec lumen env | grep POSTGRES_PORT_5432_TCP_ADDR | cut -d "=" -f2)
		sudo docker-compose exec lumen /bin/bash -c "cd /var/www/src \
			&& export PGHOST=$POSTGES_HOST_IP_ADDR \
			&& export PGPORT=5432 \
			&& export PGUSER=postgres \
			&& export PGDATABASE=postgres \
			&& export PGPASSWORD=password \
			&& /bin/bash"
		;;
	example)
		if [[ -z $DOCKER_HOST_IP ]]; then
			echo "Run 'export DOCKER_HOST_IP=<Docker Host IP address>' and retry"
			exit 1
		fi
		# See: http://nordicapis.com/build-api-lumen-micro-framework/
		curl http://${DOCKER_HOST_IP}:8000/encode?value=encodeexampletext; echo
		;;
	t | tests)
		vendor/bats/bin/bats tests/bats/
		;;
	* | h | help)
		help
		;;
esac
